### ISSUE TITLE
Allow auxiliary columns to be defined before main trace columns inside trace_columns section

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-dsl#55]
Currently inside the trace_columns section, the parser expects the main trace columns to be defined before the auxiliary columns. We should consider allowing users to define the auxiliary columns before the main columns. However, If it is preferable to keep main trace columns definition first as convention, we should show a better error to users regarding the same.

**Comment by bobbinth** [comment]
I think the order in which trace segments are defined is meaningful. So, `main` trace segment should come before `aux` trace segment. In the future, we may allow users to define their own names for trace segments, and then, whichever one comes first will be the `main` segment, and whichever comes second will be `aux` segment.

**Comment by tohrnii** [comment]
Thank you @bobbinth for the clarification. If order should take precedence over name, then we can close this issue. I've opened #57 to add clarification to the docs regarding the same.
